version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    image: jacklul/pihole:latest
    container_name: pihole
    hostname: pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "80:80/tcp"
    environment:
      TZ: ${TZ}
      WEBPASSWORD: ${WEBPASSWORD}
      FTLCONF_LOCAL_IPV4: ${FTLCONF_LOCAL_IPV4}
      PIHOLE_DNS_: ${PIHOLE_DNS_}
      #DNSSEC: "true" #this ignores CUSTOM_CACHE_SIZE
      DNSMASQ_LISTENING: all
      DHCP_ACTIVE: "true" # Required if you are using Pi-hole as your DHCP server, else not needed
      DHCP_START: ${DHCP_START} # Required if you are using Pi-hole as your DHCP server, else not needed
      DHCP_END: ${DHCP_END} # Required if you are using Pi-hole as your DHCP server, else not needed
      DHCP_ROUTER: ${DHCP_ROUTER} # Required if you are using Pi-hole as your DHCP server, else not needed
      DHCP_LEASETIME: ${DHCP_LEASETIME} # Required if you are using Pi-hole as your DHCP server, else not needed
      DHCP_IPv6: "true" # Required if you are using Pi-hole as your DHCP server, else not needed
      DHCP_rapid_commit: "true" # Required if you are using Pi-hole as your DHCP server, else not needed
      PIHOLE_DOMAIN: ${PIHOLE_DOMAIN} #defaults to "lan", comment out or configure in .env
      WEBTHEME: "default-auto"
      ADLISTS_URL: 'https://v.firebog.net/hosts/lists.php?type=tick'
      WHITELIST_URL: 'https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt'
      #REGEX_WHITELIST_URL: ''
      #BLACKLIST_URL: ''
      REGEX_BLACKLIST_URL: 'https://raw.githubusercontent.com/mmotti/pihole-regex/master/regex.list'
    # Volumes store your data between container upgrades
    volumes:
      - ${DATA}:/etc/pihole
      - ${DNSMASQ}:/etc/dnsmasq.d
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    networks:
      eth0:
        ipv4_address: 192.168.1.2 #if you comment this, it will take the first available IP from the set IP Range
    restart: always

networks:
  eth0:
    external: true
    name: eth0
